/**
 * Exam-oriented emphasis, curated for MBBS / MRCP / USMLE pathology.
 *  - bold   : high-yield diseases, mechanisms, eponyms, signs and stains (first mention per page only)
 *  - italic : organism names (Latin binomials), gene symbols, Latin phrases
 * Matching is deliberately conservative: whole words, plural tolerant, never inside headings or captions.
 */
const BOLD = `
reversible injury|irreversible injury|coagulative necrosis|liquefactive necrosis|caseous necrosis|fat necrosis|fibrinoid necrosis|gangrenous necrosis|gangrene|apoptosis|necroptosis|pyroptosis|ferroptosis|autophagy|hypoxia|ischemia|reperfusion injury|oxidative stress|reactive oxygen species|free radicals|cytochrome c|caspases|intrinsic pathway|extrinsic pathway|hydropic change|fatty change|steatosis|hyperplasia|hypertrophy|atrophy|metaplasia|dysplasia|aplasia|hypoplasia|lipofuscin|hemosiderin|dystrophic calcification|metastatic calcification|hemosiderosis|Barrett esophagus|anaplasia|
acute inflammation|chronic inflammation|chemotaxis|margination|diapedesis|transmigration|opsonization|phagocytosis|selectins|integrins|histamine|prostaglandins|leukotrienes|bradykinin|complement system|membrane attack complex|neutrophil extracellular traps|serous inflammation|fibrinous inflammation|purulent inflammation|abscess|granulomatous inflammation|granuloma|epithelioid cells|Langhans giant cells|foreign body giant cells|leukocyte adhesion deficiency|chronic granulomatous disease|Chédiak-Higashi syndrome|NADPH oxidase|myeloperoxidase|exudate|transudate|granulation tissue|regeneration|fibrosis|keloid|hypertrophic scar|primary intention|secondary intention|myofibroblasts|angiogenesis|systemic inflammatory response syndrome|acute-phase proteins|C-reactive protein|
edema|hyperemia|congestion|hemorrhage|hemostasis|thrombosis|Virchow triad|endothelial injury|stasis|hypercoagulability|embolism|pulmonary embolism|infarction|septic shock|cardiogenic shock|hypovolemic shock|disseminated intravascular coagulation|factor V Leiden|antiphospholipid syndrome|lines of Zahn|paradoxical embolism|fat embolism|amniotic fluid embolism|nutmeg liver|petechiae|purpura|ecchymoses|hematoma|anasarca|ascites|pitting edema|
autosomal dominant|autosomal recessive|X-linked recessive|X-linked dominant|Marfan syndrome|Ehlers-Danlos syndrome|familial hypercholesterolemia|cystic fibrosis|Gaucher disease|Tay-Sachs disease|Niemann-Pick disease|Fabry disease|phenylketonuria|Down syndrome|trisomy 21|Edwards syndrome|Patau syndrome|Turner syndrome|Klinefelter syndrome|fragile X syndrome|Prader-Willi syndrome|Angelman syndrome|Philadelphia chromosome|genomic imprinting|trinucleotide repeat|mitochondrial inheritance|Duchenne muscular dystrophy|DiGeorge syndrome|22q11.2 deletion syndrome|glycogen storage diseases|mucopolysaccharidoses|lysosomal storage diseases|incomplete penetrance|variable expressivity|
type I hypersensitivity|type II hypersensitivity|type III hypersensitivity|type IV hypersensitivity|anaphylaxis|atopy|Goodpasture syndrome|serum sickness|delayed-type hypersensitivity|systemic lupus erythematosus|anti-dsDNA|anti-Smith|Sjögren syndrome|systemic sclerosis|rheumatoid arthritis|immunodeficiency|severe combined immunodeficiency|X-linked agammaglobulinemia|common variable immunodeficiency|Wiskott-Aldrich syndrome|acquired immunodeficiency syndrome|amyloidosis|Congo red|apple-green birefringence|hyperacute rejection|acute rejection|chronic rejection|graft-versus-host disease|IgG4-related disease|central tolerance|peripheral tolerance|autoimmunity|
carcinoma in situ|benign tumor|malignant tumor|adenoma|papilloma|teratoma|hamartoma|choristoma|oncogenes|proto-oncogene|tumor suppressor genes|two-hit hypothesis|Warburg effect|metastasis|paraneoplastic syndromes|tumor markers|carcinoembryonic antigen|alpha-fetoprotein|prostate-specific antigen|CA-125|Reed-Sternberg cells|Li-Fraumeni syndrome|retinoblastoma|familial adenomatous polyposis|Lynch syndrome|hereditary nonpolyposis colorectal cancer|human papillomavirus|Epstein-Barr virus|aflatoxin|asbestos|carcinogenesis|epithelial-to-mesenchymal transition|
tuberculosis|Ghon complex|miliary tuberculosis|leprosy|syphilis|gonorrhea|malaria|sepsis|toxic shock syndrome|candidiasis|aspergillosis|cryptococcosis|histoplasmosis|toxoplasmosis|schistosomiasis|opportunistic infections|Negri bodies|Koplik spots|
kwashiorkor|marasmus|vitamin A deficiency|vitamin D deficiency|rickets|osteomalacia|scurvy|beriberi|pellagra|Wernicke encephalopathy|lead poisoning|carbon monoxide poisoning|obesity|metabolic syndrome|
atherosclerosis|atheroma|fatty streak|aneurysm|aortic dissection|vasculitis|giant cell arteritis|Takayasu arteritis|polyarteritis nodosa|Kawasaki disease|granulomatosis with polyangiitis|IgA vasculitis|Buerger disease|thromboangiitis obliterans|essential hypertension|malignant hypertension|hyaline arteriolosclerosis|hyperplastic arteriolosclerosis|Mönckeberg medial sclerosis|myocardial infarction|ischemic heart disease|angina pectoris|unstable angina|sudden cardiac death|heart failure|cor pulmonale|hypertrophic cardiomyopathy|dilated cardiomyopathy|restrictive cardiomyopathy|infective endocarditis|rheumatic heart disease|rheumatic fever|Aschoff bodies|mitral stenosis|mitral valve prolapse|aortic stenosis|tetralogy of Fallot|ventricular septal defect|atrial septal defect|patent ductus arteriosus|coarctation of the aorta|transposition of the great arteries|pericarditis|myocarditis|cardiac tamponade|Libman-Sacks endocarditis|varicose veins|deep vein thrombosis|superior vena cava syndrome|hemangioma|angiosarcoma|Kaposi sarcoma|
iron deficiency anemia|megaloblastic anemia|pernicious anemia|aplastic anemia|sickle cell disease|thalassemia|hereditary spherocytosis|glucose-6-phosphate dehydrogenase deficiency|hemolytic anemia|autoimmune hemolytic anemia|polycythemia vera|immune thrombocytopenic purpura|thrombotic thrombocytopenic purpura|hemophilia A|von Willebrand disease|acute lymphoblastic leukemia|acute myeloid leukemia|chronic lymphocytic leukemia|chronic myeloid leukemia|Hodgkin lymphoma|non-Hodgkin lymphoma|Burkitt lymphoma|follicular lymphoma|diffuse large B-cell lymphoma|mantle cell lymphoma|multiple myeloma|Waldenström macroglobulinemia|myelodysplastic syndromes|myeloproliferative neoplasms|essential thrombocythemia|primary myelofibrosis|Auer rods|smudge cells|Bence Jones proteins|rouleaux|hemophagocytic lymphohistiocytosis|
asthma|chronic obstructive pulmonary disease|emphysema|chronic bronchitis|bronchiectasis|acute respiratory distress syndrome|diffuse alveolar damage|hyaline membranes|lobar pneumonia|bronchopneumonia|pneumoconiosis|silicosis|asbestosis|coal workers' pneumoconiosis|sarcoidosis|idiopathic pulmonary fibrosis|usual interstitial pneumonia|hypersensitivity pneumonitis|lung abscess|pulmonary hypertension|pulmonary edema|atelectasis|pneumothorax|lung adenocarcinoma|squamous cell carcinoma|small cell carcinoma|mesothelioma|Pancoast tumor|carcinoid tumor|Curschmann spirals|Charcot-Leyden crystals|asbestos bodies|neonatal respiratory distress syndrome|nasopharyngeal carcinoma|
gastroesophageal reflux disease|achalasia|esophageal varices|peptic ulcer disease|Helicobacter pylori gastritis|autoimmune gastritis|gastric adenocarcinoma|Zollinger-Ellison syndrome|Crohn disease|ulcerative colitis|celiac disease|Whipple disease|colorectal carcinoma|adenomatous polyps|Hirschsprung disease|intussusception|appendicitis|diverticulosis|diverticulitis|ischemic colitis|necrotizing enterocolitis|carcinoid syndrome|gastrointestinal stromal tumor|pseudomembranous colitis|
viral hepatitis|alcoholic hepatitis|alcoholic liver disease|Mallory-Denk bodies|nonalcoholic fatty liver disease|cirrhosis|hepatocellular carcinoma|Wilson disease|hemochromatosis|alpha-1 antitrypsin deficiency|primary biliary cholangitis|primary sclerosing cholangitis|Budd-Chiari syndrome|jaundice|portal hypertension|hepatic encephalopathy|hepatorenal syndrome|cholelithiasis|cholecystitis|cholangiocarcinoma|acute pancreatitis|chronic pancreatitis|pancreatic adenocarcinoma|diabetes mellitus|type 1 diabetes|type 2 diabetes|diabetic ketoacidosis|insulinoma|
glomerulonephritis|nephrotic syndrome|nephritic syndrome|minimal change disease|membranous nephropathy|focal segmental glomerulosclerosis|membranoproliferative glomerulonephritis|IgA nephropathy|poststreptococcal glomerulonephritis|rapidly progressive glomerulonephritis|Alport syndrome|diabetic nephropathy|Kimmelstiel-Wilson nodules|polycystic kidney disease|renal cell carcinoma|Wilms tumor|acute tubular necrosis|acute kidney injury|chronic kidney disease|pyelonephritis|nephrolithiasis|hydronephrosis|urothelial carcinoma|benign prostatic hyperplasia|prostatic adenocarcinoma|seminoma|testicular torsion|germ cell tumors|cervical intraepithelial neoplasia|endometrial carcinoma|endometriosis|adenomyosis|leiomyoma|polycystic ovarian syndrome|hydatidiform mole|choriocarcinoma|preeclampsia|ectopic pregnancy|Meigs syndrome|
fibroadenoma|ductal carcinoma in situ|invasive ductal carcinoma|invasive lobular carcinoma|phyllodes tumor|Paget disease of the nipple|fibrocystic changes|estrogen receptor|HER2|triple-negative breast cancer|
Graves disease|Hashimoto thyroiditis|papillary carcinoma|medullary carcinoma|follicular carcinoma|anaplastic carcinoma|goiter|hyperparathyroidism|hypoparathyroidism|pituitary adenoma|prolactinoma|acromegaly|Cushing syndrome|Conn syndrome|Addison disease|pheochromocytoma|multiple endocrine neoplasia|neuroblastoma|Sheehan syndrome|diabetes insipidus|SIADH|
osteoporosis|Paget disease of bone|osteosarcoma|Ewing sarcoma|chondrosarcoma|giant cell tumor|osteoarthritis|gout|pseudogout|osteomyelitis|osteonecrosis|fibrous dysplasia|osteogenesis imperfecta|achondroplasia|osteopetrosis|rhabdomyosarcoma|leiomyosarcoma|liposarcoma|synovial sarcoma|myasthenia gravis|Guillain-Barré syndrome|polymyositis|dermatomyositis|
psoriasis|melanoma|basal cell carcinoma|actinic keratosis|pemphigus vulgaris|bullous pemphigoid|dermatitis herpetiformis|lichen planus|seborrheic keratosis|erythema multiforme|Stevens-Johnson syndrome|molluscum contagiosum|
Alzheimer disease|Parkinson disease|Huntington disease|amyotrophic lateral sclerosis|multiple sclerosis|ischemic stroke|intracerebral hemorrhage|subarachnoid hemorrhage|epidural hematoma|subdural hematoma|glioblastoma|astrocytoma|oligodendroglioma|ependymoma|meningioma|medulloblastoma|schwannoma|neurofibromatosis|tuberous sclerosis|Creutzfeldt-Jakob disease|Lewy bodies|neurofibrillary tangles|amyloid plaques|Pick disease|bacterial meningitis|brain abscess|hydrocephalus|Wallerian degeneration|Reye syndrome|retinoblastoma|diabetic retinopathy|glaucoma|macular degeneration
`.split('|').map((s) => s.trim()).filter(Boolean);

/** Short abbreviations: matched case-sensitively. */
const BOLD_ABBR = ['DIC', 'SLE', 'ARDS', 'COPD', 'GERD', 'HIV', 'AIDS', 'CML', 'CLL', 'AML', 'ALL', 'DVT', 'MI', 'TTP', 'ITP', 'HUS', 'ATN', 'FSGS', 'BPH', 'CIN', 'DCIS', 'GIST', 'MEN', 'PCOS', 'HLA-B27', 'IgA nephropathy', 'TNF', 'IL-1', 'IL-6', 'NETs'];

const GENERA = 'Staphylococcus|Streptococcus|Enterococcus|Clostridium|Clostridioides|Bacillus|Corynebacterium|Listeria|Mycobacterium|Escherichia|Klebsiella|Salmonella|Shigella|Pseudomonas|Vibrio|Campylobacter|Helicobacter|Neisseria|Haemophilus|Bordetella|Legionella|Yersinia|Treponema|Borrelia|Leptospira|Chlamydia|Chlamydophila|Rickettsia|Mycoplasma|Bartonella|Brucella|Francisella|Actinomyces|Nocardia|Bacteroides|Proteus|Enterobacter|Acinetobacter|Candida|Aspergillus|Cryptococcus|Histoplasma|Coccidioides|Blastomyces|Pneumocystis|Mucor|Rhizopus|Plasmodium|Toxoplasma|Entamoeba|Giardia|Trichomonas|Trypanosoma|Leishmania|Cryptosporidium|Schistosoma|Strongyloides|Ascaris|Taenia|Echinococcus|Trichinella|Wuchereria|Onchocerca|Cytomegalovirus|Treponema';
const SPECIES = 'aureus|epidermidis|pyogenes|agalactiae|pneumoniae|viridans|faecalis|faecium|coli|tuberculosis|leprae|avium|kansasii|pylori|jejuni|difficile|perfringens|botulinum|tetani|anthracis|diphtheriae|monocytogenes|meningitidis|gonorrhoeae|pallidum|burgdorferi|typhi|enterica|typhimurium|cholerae|aeruginosa|pestis|influenzae|jirovecii|carinii|albicans|glabrata|neoformans|fumigatus|flavus|capsulatum|immitis|dermatitidis|histolytica|falciparum|vivax|malariae|ovale|knowlesi|gondii|brucei|cruzi|lamblia|vaginalis|trachomatis|psittaci|burnetii|rickettsii|mansoni|haematobium|japonicum|stercoralis|lumbricoides|solium|granulosus|spiralis|bancrofti|volvulus|parvum|abscessus|intracellulare|ulcerans|marinum|bovis|pertussis|pneumophila|tularensis|mirabilis|cepacia|baumannii|species|spp';
const LATIN = 'in situ|in vivo|in vitro|ex vivo|de novo|post mortem|peau d’orange|peau d\'orange|et al\\.|per se|status epilepticus|ad hoc|in utero|vice versa|sine qua non|anlage|cor bovinum|ex vacuo|pro re nata';
const GENES = ['TP53', 'RB1', 'BRCA1', 'BRCA2', 'KRAS', 'NRAS', 'HRAS', 'MYC', 'MYCN', 'ERBB2', 'APC', 'BCL2', 'BCL6', 'BCR-ABL1', 'ABL1', 'JAK2', 'FLT3', 'NPM1', 'CFTR', 'HFE', 'FBN1', 'PTEN', 'VHL', 'NF1', 'NF2', 'WT1', 'RET', 'MEN1', 'CDKN2A', 'ATM', 'MLH1', 'MSH2', 'MSH6', 'PMS2', 'EGFR', 'ALK', 'BRAF', 'PIK3CA', 'IDH1', 'IDH2', 'MDM2', 'CDK4', 'CCND1', 'BAX', 'FAS', 'SMAD4', 'STK11', 'CDH1', 'SDHB', 'TSC1', 'TSC2', 'HBB', 'DMD', 'HTT', 'SOD1', 'APOE', 'PSEN1', 'PSEN2', 'APP', 'SNCA', 'LRRK2', 'PRNP', 'MECP2', 'FMR1', 'COL1A1', 'COL3A1', 'LDLR', 'GBA', 'HEXA', 'PAH', 'F8', 'F9', 'KIT', 'PDGFRA', 'RUNX1', 'PML-RARA', 'MLL', 'NOTCH1', 'TERT', 'BCL10', 'CTNNB1', 'ERG', 'TMPRSS2', 'SRY'];

const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const W = '(?<![\\p{L}\\p{N}-])';
const E_ = '(?![\\p{L}\\p{N}])';

export const BOLD_RE = new RegExp(`${W}(?:${[...BOLD].sort((a, b) => b.length - a.length).map(esc).join('|')})(?:s|es)?${E_}`, 'giu');
export const BOLD_ABBR_RE = new RegExp(`${W}(?:${BOLD_ABBR.sort((a, b) => b.length - a.length).map(esc).join('|')})${E_}`, 'gu');
export const ORGANISM_RE = new RegExp(`${W}(?:(?:${GENERA})(?:\\s+(?:${SPECIES})\\b)?|[A-Z]\\.\\s?(?:${SPECIES})\\b)${E_}`, 'gu');
export const LATIN_RE = new RegExp(`${W}(?:${LATIN})`, 'giu');
export const GENE_RE = new RegExp(`${W}(?:${GENES.map(esc).join('|')})${E_}`, 'gu');
